### ISSUE TITLE
Half slabs / stairs issue. 

### ISSUE THREAD

**Issue by J1b1x** [Matze997/Pathfinder#11]
The entity is trying to jump on a target block, even if it stands on a half slab. You'd probably need to either increase the y motion if it's standing on a half slab, or you'd need to add a high cost for half slabs, so it's walking around them.

Example video: https://youtu.be/fywTs-TTDQ8

**Comment by Matze997** [comment]
Entity navigator isn´t implemnted in the new version and probably won´t be readded
There will be an extra plugin/virion
