### ISSUE TITLE
It doesn't find the shortest way

### ISSUE THREAD

**Issue by xxAROX** [Matze997/Pathfinder#4]
![grafik](https://user-images.githubusercontent.com/57589973/151273263-75c6b08f-2d5f-46e7-b8f0-0ece39b848e1.png)

**Comment by Matze997** [comment]
Thats because A* tries to find the nearest position to the target position. You can avoid this, by multiplying the H Cost with numbers like 10000 or even more. But this will decrease the speed of the pathfinder
