### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by daniktheboss** [Matze997/Pathfinder#9]
Whats a good way to get better performance if using 10+ entities

**Comment by sn3akrr** [comment]
Use 9 entities

**Comment by buchwasa** [comment]
8 is better

**Comment by Matze997** [comment]
Set a lower value for the timeout and/or use a queue

**Comment by daniktheboss** [comment]
Or, calculate the direction the "target" is at, serialize the chunks, send them to a thread/async task, calculate using AStar and continue on.

**Comment by Matze997** [comment]
Thats true, but I'm looking for a better solution.
The way you suggested is not the way I want to go

**Comment by daniktheboss** [comment]
May you suggest how you wanted to do it?

**Comment by Matze997** [comment]
https://github.com/Matze997/Pathfinder/commit/f127371e1dcb3d969dd02926b18d5a0fdfe47e30
